### PR TITLE
Added Live Lyrics Events and Added JioSaavn in DefaultSources

### PR DESCRIPTION
**Pull request by appujet**
- Implemented live lyrics support using [LavaLyrics](https://github.com/topi314/LavaLyrics/pull/1).
- Added JioSaavn in DefaultSources
  
This update enhances the user experience by providing real-time lyrics support

### CODE REVIEW

**Comment by Tomato6966** [comment]
Looks gooder than before

Please add the following:
- check wether the plugin is enabled or not on the node via node.info
- add "map" functions on the player which call the node function for you
- e.g. player.getCurrentLyrics() -> player.node.getCurrentLyrics()

**Comment by Tomato6966** [comment]
Please rebase onto current master version (things changed in package.json and Node.ts)

+ don't update the package.json versions in this pr.

The changes related to player looks good

**Comment by Tomato6966** [comment]
I added a couple more checks and sampels to the jsdoc
Please validate, then i would merge

**Review by appujet — COMMENTED** [review]
All looks good 👍

**Pull request merged**
