### PR TITLE
Create check.yml

### PR DESCRIPTION
**Pull request by dawgcodes**
update

### CODE REVIEW

**Comment by Tomato6966** [comment]
What does that do / fix / improve?

**Comment by appujet** [comment]
> What does that do / fix / improve?

It is make PR pkg for install

**Comment by Tomato6966** [comment]
What is "PR pkg"

**Comment by appujet** [comment]
> What is "PR pkg"

https://github.com/stackblitz-labs/pkg.pr.new

**Comment by Tomato6966** [comment]
@appujet You wanted to add smt to this pr

**Comment by appujet** [comment]
This pr looking good but it is just create package of PR

**Comment by Tomato6966** [comment]
Is it required to do with pnpm?
Can we not use smt like bun or normal npm for packages?
Since it's a container there isn't a cache and thus you cannot profit from pnpm technically

I'm currently considering to approve this pr otherwise

**Review by Tomato6966 — APPROVED** [review]

**Comment by Tomato6966** [comment]
Run actions/setup-node@v4
Found in cache @ /opt/hostedtoolcache/node/20.17.0/x64
Environment details
/usr/local/bin/pnpm store path --silent
/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23509
              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);
                    ^

UsageError: This project is configured to use yarn because /home/runner/work/lavalink-client/lavalink-client/package.json has a "packageManager" field
    at Engine.findProjectSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23509:21)
    at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23539:24)
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24232:5) {
  clipanion: { type: 'usage' }
}

Node.js v20.17.0
Error: /usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23509
              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);
                    ^

UsageError: This project is configured to use yarn because /home/runner/work/lavalink-client/lavalink-client/package.json has a "packageManager" field
    at Engine.findProjectSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23509:21)
    at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23539:24)
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24232:5) {
  clipanion: { type: 'usage' }
}

Node.js v20.17.0

**Comment by Tomato6966** [comment]
@dawgcodes

**Pull request merged**
