### PR TITLE
fix and format lint

### PR DESCRIPTION
**Pull request by LucasB25**
- Remove eslint for biom
- Update All packages 
- Fixed a lot of logic in the code

### CODE REVIEW

**Comment by Tomato6966** [comment]
What is biome.json
Why remove eslint
Why apply subjective design rules
I use my own Formatter

**Comment by LucasB25** [comment]
Biom is much more powerful than eslint allowing you to have cleaner code overall, if you want to have customization biom allows you to do that too just take a look at the docs 

With biom alone I can correct logic errors that were found in the code, the tool is much more powerful and customizable and there is no strict mode

**Comment by EvilG-MC** [comment]
> What is biome.json Why remove eslint Why apply subjective design rules I use my own, not strict, Formatter

Biome is a linter and formatter, is faster than eslint but it does not have as many rules as eslint and can cause certain problems due to the lack of rules, even breaking the code if it is not checked manually because biome often changes certain aspects of the code.

**Comment by LucasB25** [comment]
> > What is biome.json Why remove eslint Why apply subjective design rules I use my own, not strict, Formatter
> 
> Biome is a linter and formatter, is faster than eslint but it does not have as many rules as eslint and can cause certain problems due to the lack of rules, even breaking the code if it is not checked manually because biome often changes certain aspects of the code.
 
It's true but there are more and more rules that have been put in place, currently I have checked as best I can so that he does not break the code

**Comment by EvilG-MC** [comment]
> > > What is biome.json Why remove eslint Why apply subjective design rules I use my own, not strict, Formatter
> > 
> > 
> > Biome is a linter and formatter, is faster than eslint but it does not have as many rules as eslint and can cause certain problems due to the lack of rules, even breaking the code if it is not checked manually because biome often changes certain aspects of the code.
> 
> It's true but there are more and more rules that have been put in place, currently I have checked as best I can so that he does not break the code. But a second check would surely be a good idea in order to apply new rules or remove them.

As far as I can see, most of the changes are in imports, spacing and styling that *apparently* don't seem to affect how the code works, but the final decision is up to tomato.

**Comment by Tomato6966** [comment]
I don't think we need a formatter and linter except eslint, there's a reason you use eslint.
Formatting is just choice and personal preference
If it doesn't provide any convencience, as i can see there are none, then there is no need to switch from eslint to biome

also if you propse such changes, simply make an issue / pr for the package.json and config files, not what actually the "new linter" would do..

**Comment by Tomato6966** [comment]
I have decided to not switch from eslint (which is totally fine and perfect for my use: checking wether i have not ts related bugs or not) to biome.

I will only switch, when there is a significant advantage.

Currently biome, is only opinionated, not highly configurable, and all there "points" are: "Eslint" / "Prettier" don't support that, tho they do, if you config it correctly.

**Comment by LucasB25** [comment]
I understand but Biom has many more advantages than eslint 

- Faster 
- More stable
- No expense on plugins 
- A great customization 
- It provides the errors and suggests or tells you how to correct them while respecting the typescript rules (which is not always respected in the code)
- ...

**Pull request closed without merging**
