### PR TITLE
Update packages and typescript

### PR DESCRIPTION
**Pull request by hwangsihu**

### CODE REVIEW

**Comment by Tomato6966** [comment]
Completly unecessary commit

**Comment by LucasB25** [comment]
Not necessary but no reason to refuse it, since it contains package updates and improved code readability

**Comment by EvilG-MC** [comment]
Is it just me or did he modify the `dist` files directly?

**Comment by LucasB25** [comment]
> Is it just me or did he modify the `dist` files directly?

I hadn’t seen lmao

**Comment by hwangsihu** [comment]
> > Is it just me or did he modify the `dist` files directly?
> 
> I hadn’t seen lmao

No, I ran NPM RUN Build and it was like this.

**Comment by Tomato6966** [comment]
I will not approve this or any other commits/PRs if they contain changes within the dist/docs folder.

Please make sure to remove all changes related to that, then i will review the PR

The dist and docs folder get generated by me on a version publish

**Comment by hwangsihu** [comment]
Done.

**Comment by Tomato6966** [comment]
Now i can see what you did:
- Update the versions on package.json ( I will do it via dependabot / manually don't worry)
- Remove eslint
Why you want to get rid of eslint?

**Comment by hwangsihu** [comment]
What? I didn't uninstall ESLint. I just changed the version to v9 and migrated.

**Comment by Tomato6966** [comment]
Ah my bad
didn't see that you also changed to eslint flat config

**Pull request merged**
