### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by hwangsihu**

### CODE REVIEW

**Comment by Tomato6966** [comment]
As stated in 3 other PRs, i am handling the versioning of dependencies but this commit looks good, i will check it out when im on my pc again

**Comment by Tomato6966** [comment]
Thanks!

**Comment by hwangsihu** [comment]
Sorry to ask here, but why do you want to manage your package only with dependabot? Looking at the PR, it looks like dependabot won't submit the PR even though have a newer version.

**Comment by Tomato6966** [comment]
I manage it manually, whenever i release smt, i don't want to release a new version just because of a dependency update, i connected dependabot to retrieve notifications for vulnarabilities in case some happen

**Comment by hwangsihu** [comment]
If you don't want to release a new version because of the package, you can just not release it and release it when new features come out
Anyway, I see.

**Pull request merged**
