### PR TITLE
added new

### PR DESCRIPTION
**Pull request by appujet**
- added: [lyrics, jiosaavn](https://github.com/Tomato6966/lavalink-client/commit/a3849a5d66f920ba6012f3cbc617783e30f2f093)
- change: format

### CODE REVIEW

**Comment by EvilG-MC** [comment]
I really don't know what was the purpose of... doing this.

image

Basically this PR would ruin tsdocs, the ability to install from github and surely several things that biome changed with the formatter.

Not to mention the fact that it's too many things for one PR, I think and maintain that each change should be done in a different PR and not just one.

Also create a branch for the changes so as not to ruin the original branch in case of a problem.

**Comment by MARCROCK22** [comment]
why you added dist to .gitignore file?

**Comment by appujet** [comment]
> why you added dist to .gitignore file?

The `dist` folder is added to `.gitignore` because it's generated during the build process. It's not needed in the repository since users can recreate it by running the build command after installing dependencies. This keeps the repo clean and avoids unnecessary conflicts or large file sizes.

**Comment by appujet** [comment]
> I really don't know what was the purpose of... doing this.
> 
> image
> 
> Basically this PR would ruin tsdocs, the ability to install from github and surely several things that biome changed with the formatter.
> 
> Not to mention the fact that it's too many things for one PR, I think and maintain that each change should be done in a different PR and not just one.
> 
> Also create a branch for the changes so as not to ruin the original branch in case of a problem.


For cleaner code and better code structure. If you mentioned any problems, you can review it yourself by running:  
`pnpm add https://pkg.pr.new/appujet/lavalink-client@87fc00b`

**Comment by Tomato6966** [comment]
lyrics are already supported by lavalink-client by doing
node.request

**Comment by Tomato6966** [comment]
Can't review the PR because every file is "modified" completly, therefore i can'T review the changes.

**Comment by appujet** [comment]
> lyrics are already supported by lavalink-client by doing node.request

also added live lyrics event

**Pull request closed without merging**
