### PR TITLE
enforce type

### PR DESCRIPTION
**Pull request by EvilG-MC**
The `getPlayer` method always returns the `Player` type, even though it may be `undefined` the solution is to force the type to make sure in case of typescript users it is `Player | undefined`.

### CODE REVIEW

**Comment by Tomato6966** [comment]
There is literally no type change

map.get() is on default returns: Value | undefined
In this case: players.get() returns: Player | undefined
image

**Comment by Tomato6966** [comment]
There is no need of enforcing, that's what i mean

**Comment by EvilG-MC** [comment]
Well...

image

**Comment by EvilG-MC** [comment]
If I go to the type definition:

image

**Comment by Tomato6966** [comment]
ok

**Comment by EvilG-MC** [comment]
That's why I *enforce* the type

**Comment by Tomato6966** [comment]
Thanks

**Comment by EvilG-MC** [comment]
Sounds good to me! Thanks

**Comment by Tomato6966** [comment]
I merged it, and will add more type enforcements with the v2.4.x release, thanks

**Pull request merged**
